### ISSUE TITLE
Sacré boulot

### ISSUE THREAD

**Issue by Pascal66** [NicolasBcg/horse_race_results_pred#1]
J'ai encore des problèmes avec les FANTOMES_ mais je m'amuse
![image](https://github.com/user-attachments/assets/5f832537-aa76-4db6-8163-28eda0f98bca)
J'en suis à cette étapes (juste 4 courses pour tester, sans utiliser ZEturf)
training end 0.28453564643859863
extracting test data 
predicting 
Model Accuracy: 68.21%
Log Loss:
0.6872276607372926

**Comment by NicolasBcg** [comment]
Bonjour,

Je suis ravi d'avoir pu vous aider, auriez vous un peu de temps pour
discuter de possibles amélioration?
Aussi, je vois que vous avez des résultats plutôt intéressant, accepteriez
vous de m'en dire plus concernant le modèle entrainé par exemple et les
données sur lesquelles vous l'avez entrainé.

**Comment by NicolasBcg** [comment]
Aussi, je suis actuellement en recherche d'emploi dans la data/IA, je
suppose que c'est votre domaine et que vous avez surement des contactes. Si
vous pouvez m'aider, par exemple en me mettant en relation avec des
personnes recherchant à embaucher dans ce domaine j'apprécierai fortement
le geste. Je viens d'être diplômé et c'est assez compliqué de trouver un
premier emploi dans ce domaine c'est pourquoi je fais appel à votre aide.

Le lun. 11 nov. 2024 à 11:15, Nicolas Bocage ***@***.***> a
écrit :

**Comment by NicolasBcg** [comment]
Je serais ravi d'en discuter d'avantage et d'avancer plus sur ce projet. Aurais tu un peu de temps en fin de semaine où l'on pourrait faire une visio pour en discuter ?
