### ISSUE TITLE
D_Encode_new_data

### ISSUE THREAD

**Issue by Pascal66** [NicolasBcg/horse_race_results_pred#4]
https://github.com/NicolasBcg/horse_race_results_pred/blob/6439168602c9bb517479732ff8a096a77e45d5c2/code_v5/D_encode.py#L112C1-L113C39

Petit soucis ici non ? Tu ne filtres pas sur les dates.
    df = df[df.dateReunion >= date1 * 1000]
    df = df[df.dateReunion < date2 * 1000]

**Comment by NicolasBcg** [comment]
Le champs dateRéunion est en fait un entier qui est le nombre de secondes écoulée depuis 1970 donc cela filtre bien sur les dates
il me semble

**Comment by NicolasBcg** [comment]
désolé, je pense pas que ton problème vienne de là, je fais tourner avec 16 Go de RAM et ça marche très bien sur un dataset initial avec 6 ans de données.

**Comment by NicolasBcg** [comment]
Tu devrais regarder ton dataset initial, il y a un "bug" que je n'ai pas corrigé. supposont ton dataset s'appelle AAA, si tu regénere un dataset avec le même nom, les données vont juste s'ajouter a ton précédent dataset (il y aura pas d'overwrite). C'est un problème j'en suis conscient mais je n'ai pas fais le changement. Pour le moment, je me contente juste d'effacer l'ancien dataset avant d'en recréer un ou de changer le nom du nouveau dataset. Aussi avec mon modèle de données tu n'as généralement pas besoin de regénérer le dataset à chaque tests

**Comment by NicolasBcg** [comment]
moins de 64 colonnes avec 300.000 lignes ça va être compliqué. pour réduire les colonnes tu va devoir réduire les features et 300k lignes ça devrait se faire en fonction de ton nombre de courses, y'a en moyennes entre 220 et 275 lignes par courses en fonction du nombre de fantomes
